###################
### KEYBINDINGS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/
# See https://wiki.hypr.land/Configuring/Binds/


# Sets "Windows" key as main modifier
$mainMod = SUPER


bind = $mainMod, SPACE, exec, $menu
bind = $mainMod, RETURN, exec, $terminal

bind = $mainMod, F, exec, $fileManager
bind = $mainMod, Z, exec, $browser

bind = $mainMod, Q, killactive,
bind = $mainMod, M, exit,


# Dwindle
bind = $mainMod, P, pseudo,
bind = $mainMod, O, togglesplit,


source = ~/.config/hypr/hyprland/keybindings/window.conf

source = ~/.config/hypr/hyprland/keybindings/screenshot.conf

source = ~/.config/hypr/hyprland/keybindings/workspace.conf

source = ~/.config/hypr/hyprland/keybindings/multimedia.conf

