# Fullscreen screenshot
bind =         , Print, exec, hyprshot -z -m output -m active --clipboard-only
bind = $mainMod, Print, exec, hyprshot -z -m output -m active -o ~/Pictures/Screenshots

# Region screenshot 
bind =          SHIFT, Print, exec, hyprshot -z -m region --clipboard-only
bind = $mainMod SHIFT, Print, exec, hyprshot -z -m region -o ~/Pictures/Screenshots

# Window screenshot
bind =          CTRL, Print, exec, hyprshot -z -m window --clipboard-only
bind = $mainMod CTRL, Print, exec, hyprshot -z -m window -o ~/Pictures/Screenshots

